---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -s .
  ansible-lint
platforms:
  - name: github-download
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: ${MOLECULE_PREBUILT:-true}
provisioner:
  name: ansible
  options:
    verbose: true
verifier:
  name: ansible
